language: node_js
node_js:
  - "node"

script:
  - npm install -g firebase-tools@latest
  - npm install
  - rm node_modules/@turf/invariant/index.mjs
  - npm run build:prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --only hosting